# Product table
productTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: productId
        AttributeType: S
    KeySchema:
      - AttributeName: productId
        KeyType: HASH

# Order table
orderTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: orderId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    KeySchema:
      - AttributeName: orderId
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
